language: node_js
node_js:
  - 16

# cache:
#   directories:
#     - node_modules

install:
  - npm install -g serverless
  - cd backend
  - rm -rf package-lock.json npm-shrinkwrap.json node_modules
  - npm cache clean --force
  - npm cache verify
  - npm install

before_script:
 - npm run test

script:
  - cd backend # may need to change
  - serverless deploy -v 
